---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 60...100
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 90%
ignore:
  - setup.py
  - src/upper_envelope/shared.py
  - tests/*
  - tests/**/*
  - .tox/**/*
