---
name: upper-envelope
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist

  # Package dependencies
  - numpy
  - scipy
  - numba
  - jax

  # Misc
  - black
  - nb_black
  - flake8
  - jupyterlab
  - pdbpp
  - pre-commit
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify
  - tox-conda
  - pip:
      - blackcellmagic
      - furo
      - -e .  # Install locally
